name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.7.0
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  mockito: ^5.4.4
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
